# 使用 Golang 官方提供的基础镜像
FROM golang:latest

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    GOPROXY=https://goproxy.cn,direct
# 设置工作目录
WORKDIR /app

# 复制应用程序文件到镜像中
COPY . .



# 编译应用程序
RUN go build -o main .

EXPOSE 8080

# 设置容器启动命令
CMD ["./main"]
